name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: build image
        run: docker build ./api/-t parsuvanath/projerc22:latest
      - name: push image to docker hub
        run:
          docker login -u PARSUVANATH -p ${{secrets.DOCKER_USER_NAME}}
          docker push parsuvanath/projerc22:latest
